export { default as useStaticProps } from './useStaticProps'
export { default as useKeyEvent } from './useKeyEvent'
export { default as useToggle } from './useToggle'
export { default as useDebounce } from './useDebounce'
export { default as useHighlightInput } from './useHighlightInput'
