export { ReactComponent as Copy } from './114-copy-16.svg'
export { ReactComponent as ThinClose } from './141-close-12.svg'
export { ReactComponent as Info } from './018-info-16.svg'
export { ReactComponent as Show } from './104-view-16.svg'
export { ReactComponent as Hide } from './142-close-16.svg'
export { ReactComponent as Close } from './026-close-8.svg'
