import { cloneElement, type ReactElement, type ReactNode } from 'react'

import { type ChartColorScheme } from './chartConstants'

export const chartGradientsVertical = {
  blue: (
    <linearGradient
      id='gradient-blue-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--blue-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--blue-bar-bottom)'
      />
    </linearGradient>
  ),
  lightBlue: (
    <linearGradient
      id='gradient-blue-300-100-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--blue-100-300)'
      />
      <stop
        offset='100%'
        stopColor='var(--blue-300-100)'
      />
    </linearGradient>
  ),
  aqua: (
    <linearGradient
      id='gradient-aqua-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--aqua-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--aqua-bar-bottom)'
      />
    </linearGradient>
  ),
  lightAqua: (
    <linearGradient
      id='gradient-aqua-300-100-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--aqua-100-300)'
      />
      <stop
        offset='100%'
        stopColor='var(--aqua-300-100)'
      />
    </linearGradient>
  ),
  fuchsia: (
    <linearGradient
      id='gradient-fuchsia-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--fuchsia-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--fuchsia-bar-bottom)'
      />
    </linearGradient>
  ),
  peach: (
    <linearGradient
      id='gradient-peach-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--peach-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--peach-bar-bottom)'
      />
    </linearGradient>
  ),
  lightFuchsia: (
    <linearGradient
      id='gradient-fuchsia-300-100-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--fuchsia-100-300)'
      />
      <stop
        offset='100%'
        stopColor='var(--fuchsia-300-100)'
      />
    </linearGradient>
  ),
  lightPeach: (
    <linearGradient
      id='gradient-peach-300-100-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--peach-100-300)'
      />
      <stop
        offset='100%'
        stopColor='var(--peach-300-100)'
      />
    </linearGradient>
  ),
  purple: (
    <linearGradient
      id='gradient-purple-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--purple-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--purple-bar-bottom)'
      />
    </linearGradient>
  ),
  yellow: (
    <linearGradient
      id='gradient-yellow-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--yellow-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--yellow-bar-bottom)'
      />
    </linearGradient>
  ),
  green: (
    <linearGradient
      id='gradient-green-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--green-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--green-bar-bottom)'
      />
    </linearGradient>
  ),
  red: (
    <linearGradient
      id='gradient-red-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--red-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--red-bar-bottom)'
      />
    </linearGradient>
  ),
  cyan: (
    <linearGradient
      id='gradient-cyan-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--cyan-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--cyan-bar-bottom)'
      />
    </linearGradient>
  ),
  orange: (
    <linearGradient
      id='gradient-orange-600-400-vertical'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--orange-bar-top)'
      />
      <stop
        offset='100%'
        stopColor='var(--orange-bar-bottom)'
      />
    </linearGradient>
  )
}

/**
 * Vertical opacity-fade gradients (solid top → transparent bottom) — for stacked charts.
 */
export const chartGradientsFade: Record<ChartColorScheme, ReactElement> = {
  blue: (
    <linearGradient
      id='gradient-blue-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--blue-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--blue-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--blue-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  aqua: (
    <linearGradient
      id='gradient-aqua-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--aqua-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--aqua-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--aqua-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  fuchsia: (
    <linearGradient
      id='gradient-fuchsia-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--fuchsia-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--fuchsia-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--fuchsia-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  peach: (
    <linearGradient
      id='gradient-peach-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--peach-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--peach-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--peach-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  purple: (
    <linearGradient
      id='gradient-purple-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--purple-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--purple-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--purple-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  yellow: (
    <linearGradient
      id='gradient-yellow-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--yellow-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--yellow-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--yellow-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  green: (
    <linearGradient
      id='gradient-green-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--green-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--green-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--green-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  red: (
    <linearGradient
      id='gradient-red-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--red-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--red-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--red-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  cyan: (
    <linearGradient
      id='gradient-cyan-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--cyan-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--cyan-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--cyan-500)'
        stopOpacity='0'
      />
    </linearGradient>
  ),
  orange: (
    <linearGradient
      id='gradient-orange-fade-500'
      x1='0'
      x2='0'
      y1='0'
      y2='1'
    >
      <stop
        offset='0%'
        stopColor='var(--orange-500)'
        stopOpacity='1.0'
      />
      <stop
        offset='40%'
        stopColor='var(--orange-500)'
        stopOpacity='0.4'
      />
      <stop
        offset='100%'
        stopColor='var(--orange-500)'
        stopOpacity='0'
      />
    </linearGradient>
  )
}

export const getChartGradientsVertical = (
  gradientNames: ChartColorScheme[]
): ReactNode =>
  gradientNames.map((name, index) =>
    cloneElement(chartGradientsVertical[name], {
      key: `gradient-vertical-${name}-${index}`
    })
  )

export const getChartGradientsFade = (
  gradientNames: ChartColorScheme[]
): ReactNode =>
  gradientNames.map((name, index) =>
    cloneElement(chartGradientsFade[name], {
      key: `gradient-fade-${name}-${index}`
    })
  )
