name: Publish package

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.event.actor.login != 'github-actions'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 919414
          private-key: ${{ secrets.WEKA_VERSION_BUMPER_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          scope: '@weka'

      - run: yarn install

      - run: echo "lines=$(git diff package.json | grep '+\s*"version"' -c)" >> $GITHUB_OUTPUT
        id: version-diff

      - run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'

      - run: yarn publish --minor
        if: ${{ steps.version-diff.outputs.lines == 0 }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn publish
        if: ${{ steps.version-diff.outputs.lines == 1 }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git push
        name: Push commit with new version
        if: ${{ steps.version-diff.outputs.lines == 0 }}
